### ISSUE TITLE
Qt5 applications segfault when losing focus while Byeoru is still composing

### ISSUE THREAD

**Issue by ThisIsPIRI** [uim/uim#148]
I [reported this to KDE devs](https://bugs.kde.org/show_bug.cgi?id=408760) who told me to report it here.

Qt5 applications like Kate, Konsole and QDbusViewer segfault when they lose focus(from alt-tabbing, clicking outside or switching desktops) while Byeoru is still composing a Korean letter. Everything else works fine.

Layout: Hangul 2-beol Windows
OS: Arch Linux(all software from Arch repos)
uim: 1.8.8-4
qt5-base: 5.13.0-7
Desktop: Plasma, kwin: 5.16.5-1
Trace:

```
Application: Kate (kate), signal: Segmentation fault
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7faaae539c80 (LWP 8440))]

Thread 3 (Thread 0x7faaa78c2700 (LWP 8442)):
#0  0x00007faab2b08667 in poll () from /usr/lib/libc.so.6
#1  0x00007faab0c49a80 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007faab0c49b51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007faab30ab9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007faab30525ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007faab2e852f5 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007faab32e3b37 in ?? () from /usr/lib/libQt5DBus.so.5
#7  0x00007faab2e86520 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007faab17ea57f in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007faab2b130e3 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7faaad5d4700 (LWP 8441)):
#0  0x00007faab2b08667 in poll () from /usr/lib/libc.so.6
#1  0x00007faab1a13630 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007faab1a152db in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007faaadfa6049 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007faab2e86520 in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007faab17ea57f in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007faab2b130e3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7faaae539c80 (LWP 8440)):
[KCrash Handler]
#6  0x00007faab30538af in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#7  0x00007faaae0f0fbc in QUimPlatformInputContext::commitString(QString const&) () from /usr/lib/qt/plugins/platforminputcontexts/libuimplatforminputcontextplugin.so
#8  0x00007faaae0f1042 in QUimPlatformInputContext::commit_cb(void*, char const*) () from /usr/lib/qt/plugins/platforminputcontexts/libuimplatforminputcontextplugin.so
#9  0x00007faaae0d1a3d in ?? () from /usr/lib/libuim.so.8
#10 0x00007faaa7bac807 in ?? () from /usr/lib/libuim-scm.so.0
#11 0x00007faaa7baca79 in ?? () from /usr/lib/libuim-scm.so.0
#12 0x00007faaa7bacb80 in ?? () from /usr/lib/libuim-scm.so.0
#13 0x00007faaa7bacd07 in ?? () from /usr/lib/libuim-scm.so.0
#14 0x00007faaa7bac10e in ?? () from /usr/lib/libuim-scm.so.0
#15 0x00007faaa7bac559 in ?? () from /usr/lib/libuim-scm.so.0
#16 0x00007faaa7baca79 in ?? () from /usr/lib/libuim-scm.so.0
#17 0x00007faaa7bacb80 in ?? () from /usr/lib/libuim-scm.so.0
#18 0x00007faaa7bac807 in ?? () from /usr/lib/libuim-scm.so.0
#19 0x00007faaa7baca79 in ?? () from /usr/lib/libuim-scm.so.0
#20 0x00007faaa7bb7963 in ?? () from /usr/lib/libuim-scm.so.0
#21 0x00007faaa7bac7ec in ?? () from /usr/lib/libuim-scm.so.0
#22 0x00007faaa7baca79 in ?? () from /usr/lib/libuim-scm.so.0
#23 0x00007faaa7bad094 in ?? () from /usr/lib/libuim-scm.so.0
#24 0x00007faaac00125d in GCROOTS_call_with_gc_ready_stack () from /usr/lib/libgcroots.so.0
#25 0x00007faaa7bbc644 in uim_scm_callf () from /usr/lib/libuim-scm.so.0
#26 0x00007faaae0cfd4b in uim_focus_out_context () from /usr/lib/libuim.so.8
#27 0x00007faaae0ef2de in QUimPlatformInputContext::unsetFocus() () from /usr/lib/qt/plugins/platforminputcontexts/libuimplatforminputcontextplugin.so
#28 0x00007faab3561fa9 in QGuiApplicationPrivate::_q_updateFocusObject(QObject*) () from /usr/lib/libQt5Gui.so.5
#29 0x00007faab3568abd in QGuiApplicationPrivate::processActivatedEvent(QWindowSystemInterfacePrivate::ActivatedWindowEvent*) () from /usr/lib/libQt5Gui.so.5
#30 0x00007faab356df80 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#31 0x00007faab354637c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#32 0x00007faaadfa6fec in ?? () from /usr/lib/libQt5XcbQpa.so.5
#33 0x00007faab0c47cf4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#34 0x00007faab0c49b11 in ?? () from /usr/lib/libglib-2.0.so.0
#35 0x00007faab0c49b51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#36 0x00007faab30ab9a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#37 0x00007faab30525ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#38 0x00007faab305a326 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#39 0x000055ae68a6e4d4 in ?? ()
#40 0x00007faab2a3dee3 in __libc_start_main () from /usr/lib/libc.so.6
#41 0x000055ae68a6fb3e in _start ()
[Inferior 1 (process 8440) detached]

```

**Comment by PositivePaulo** [comment]
I have the same issue when composing in Chinese. I'm also using a KDE 5 environment.

**Comment by kou** [comment]
Does the following patch solve this problem?

```diff
diff --git a/qt5/immodule/quimplatforminputcontext.cpp b/qt5/immodule/quimplatforminputcontext.cpp
index 5bf3d6b3..96ed7de9 100644
--- a/qt5/immodule/quimplatforminputcontext.cpp
+++ b/qt5/immodule/quimplatforminputcontext.cpp
@@ -630,7 +630,10 @@ void QUimPlatformInputContext::commitString(const QString& str)
 {
     QInputMethodEvent e;
     e.setCommitString(str);
-    QCoreApplication::sendEvent(qApp->focusObject(), &e);
+    QObject *focusedObject = qApp->focusObject();
+    if (focusedObject) {
+        QCoreApplication::sendEvent(focusedObject, &e);
+    }
 
     m_isAnimating = false;
 }
```
